system:
    default:
        yui:
            modules:
                # use your prefix, not "ez-"
                ezconf-listapplugin: #Â should match the first parameter of YUI.add
                    requires: ['ez-pluginregistry', 'plugin', 'base', 'ezconf-listview'] # depends on the plugin code
                    dependencyOf: ['ez-platformuiapp']
                    path: %extending_platformui.public_dir%/js/apps/plugins/ezconf-listappplugin.js
                ezconf-navigationplugin:
                    requires: ['ez-pluginregistry', 'ez-viewservicebaseplugin', 'ez-navigationitemview']
                    dependencyOf: ['ez-navigationhubviewservice']
                    path: %extending_platformui.public_dir%/js/views/services/plugins/ezconf-navigationplugin.js
                ezconf-listview:
                    requires: ['ez-templatebasedview', 'ezconflistview-ez-template']
                    path: %extending_platformui.public_dir%/js/views/ezconf-listview.js
                ezconflistview-ez-template: # internal view name + '-ez-template' suffix
                    type: 'template' # mandatory so that the template is available in JavaScript
                    path: %extending_platformui.public_dir%/templates/ezconflistview.hbt
